Repository theme-next/hexo-theme-next, pull requests merged in 2018-03, with the labels that each got.

#153 Fixes for GitHub banner option.
  source/css/_common/components/header/github-banner.styl
  source/css/_mixins/base.styl
Labels: Bug

#155 remove style table-layout: fixed;
  source/css/_common/scaffolding/tables.styl
Labels: Bug

#160 FIX ISSUE TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: Configurations

#161 FIX FIG MARGIN
  source/css/_common/components/post/post-expand.styl
Labels: CSS

#166 Updated README.
  README.md
Labels: Docs

#156 Added sub-menu feature.
  layout/_layout.swig
  layout/_macro/menu/menu-badge-1.swig
  layout/_macro/menu/menu-badge-2.swig
  layout/_macro/menu/menu-item.swig
  layout/_partials/header.swig
  layout/_partials/sub-menu.swig
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Pisces/_sub-menu.styl
  source/css/_schemes/Pisces/index.styl
  source/js/src/utils.js
Labels: Help wanted, Need Confirm

#130 Improve accessibility
  languages/_en.yml
  layout/_partials/head/head.swig
  layout/_partials/header.swig
  layout/_partials/pagination.swig
Labels: Optimization

#115 Fix duplicate meta tag keywords
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
  layout/_partials/head/head-unique.swig
Labels: Breaking Change, Bug, Hexo, Optimization

#171 Fix single quotes in lean-analytics.swig are not escaped
  _config.yml
  layout/_third-party/analytics/lean-analytics.swig
Labels: Bugfix

#167 New Crowdin translations
  languages/ar.yml
  languages/bg.yml
  languages/bn.yml
  languages/cs.yml
  languages/da.yml
  languages/de.yml
  languages/el.yml
  languages/es.yml
  languages/et.yml
  languages/fa.yml
  languages/fi.yml
  languages/fr.yml
  languages/he.yml
  languages/hi.yml
  languages/hr.yml
  languages/hu.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/jv.yml
  languages/ko.yml
  languages/lt.yml
  languages/lv.yml
  languages/ms.yml
  languages/nl.yml
  languages/no.yml
  languages/pa.yml
  languages/pl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ro.yml
  languages/ru.yml
  languages/sl.yml
  languages/sr.yml
  languages/sv.yml
  languages/th.yml
  languages/tr.yml
  languages/uk.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: Help wanted

#168 Remove keywords in Theme-Next
  _config.yml
  layout/_partials/head/head-unique.swig
Labels: Breaking Change, Bugfix, Hexo, Optimization

#173 Fix svg confict in algolia vender
  docs/ALGOLIA-SEARCH.md
  docs/zh-CN/ALGOLIA-SEARCH.md
  source/css/_common/components/third-party/algolia-search.styl
Labels: 3rd party service, Bugfix

#174 Add EN doc for leancloud counter security
  docs/LEANCLOUD-COUNTER-SECURITY.md
  docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
Labels: Docs

#175 Fix a typo in LEANCLOUD-COUNTER-SECURITY.md
  docs/LEANCLOUD-COUNTER-SECURITY.md
Labels: Docs

#185 Add comment count in mobile
  source/css/_common/components/post/post-meta.styl
Labels: Feature

#194 Update codeblock style and add border-radius settings
  _config.yml
  source/css/_common/components/highlight/highlight.styl
Labels: Feature

#195 Refactor footer icon with animation
  _config.yml
  layout/_partials/footer.swig
  source/css/_common/components/footer/footer.styl
Labels: Breaking Change, Feature

#198 Add code-of-couduct.md
  .github/CODE_OF_CONDUCT.md
  docs/zh-CN/CODE_OF_CONDUCT.md
Labels: Docs
