Repository theme-next/hexo-theme-next, pull requests merged in 2018-05, with the labels that each got.

#267 Add avatar round & opacity & animation feature
  _config.yml
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  source/css/_common/components/sidebar/sidebar-author.styl
Labels: Breaking Change, Feature

#275 Add support for automatic equation numbering for Mathjax, update the related documentation
  docs/MATH.md
  docs/zh-CN/MATH.md
  layout/_third-party/math/mathjax.swig
Labels: Feature

#253 Added custom language support feature.
  layout/_layout.swig
  layout/_macro/post-copyright.swig
  layout/_macro/post.swig
  layout/_macro/reward.swig
  layout/_macro/sidebar.swig
  layout/_macro/wechat-subscriber.swig
  layout/_partials/footer.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/header/brand.swig
  layout/_partials/header/index.swig
  layout/_third-party/comments/disqus.swig
  layout/archive.swig
  layout/category.swig
  layout/index.swig
  layout/page.swig
  layout/post.swig
  layout/schedule.swig
  layout/tag.swig
  scripts/merge-configs.js
Labels: Feature

#254 Allow customized copyright contents
  layout/_macro/post-copyright.swig
Labels: Feature

#293 Force scroll_to_more anchor to be #more
  layout/_macro/post.swig
Labels: Bugfix
