Repository theme-next/hexo-theme-next, pull requests merged in 2018-11, with the labels that each got.

#452 Fix the error when the Chinese is included in the hash
  source/js/src/utils.js
Labels: Bugfix

#463 Global improvement for ExtURL & refactored Creative Commons copyright.
  _config.yml
  layout/_macro/menu/menu-item.swig
  layout/_macro/post-collapse.swig
  layout/_macro/post-copyright.swig
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/comments.swig
  layout/_partials/footer.swig
  layout/_partials/post-copyright.swig
  layout/_third-party/github-banner.swig
  scripts/filters/after_post_render/exturl.js
  scripts/helpers/engine.js
  scripts/helpers/next-url.js
  scripts/tags/exturl.js
  source/css/_common/components/header/menu.styl
  source/css/_common/components/pages/archive.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-copyright.styl
  source/css/_common/components/post/post-title.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/sidebar/sidebar-blogroll.styl
  source/css/_common/scaffolding/base.styl
  source/css/_mixins/base.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Muse/_menu.styl
  source/css/_schemes/Pisces/_menu.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/js/src/schemes/pisces.js
Labels: Breaking Change, Bugfix, CSS, Feature, Need Review, Optimization

#465 Reward be more intelligent, related issue #280
  _config.yml
  layout/_macro/post.swig
  layout/_macro/reward.swig
  source/css/_common/components/post/post.styl
Labels: Breaking Change, Optimization

#464 add gitalk comment system
  _config.yml
  layout/_partials/comments.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/index.swig
  source/css/_common/components/third-party/gitalk.styl
  source/css/_common/components/third-party/third-party.styl
Labels: Docs, Feature

#488 Fix mathjax overflow
  layout/_third-party/math/mathjax.swig
Labels: Bugfix, Need Review
