Repository theme-next/hexo-theme-next, pull requests merged in 2018-08, with the labels that each got.

#362 New Crowdin translations
  languages/ja.yml
Labels: i18n

#359 simplify post-reward.styl
  source/css/_common/components/post/post-reward.styl
Labels: Optimization

#355 Add Labels Rules guideline
  .github/CONTRIBUTING.md
  docs/zh-CN/CONTRIBUTING.md
Labels: Docs

#386 New Crowdin translations
  languages/ja.yml
Labels: i18n
