Repository theme-next/hexo-theme-next, pull requests merged in 2018-12, with the labels that each got.

#493 Improve highlighting for Lisps
  source/css/_common/components/highlight/highlight.styl
Labels: CSS

#476 Menu external url
  _config.yml
  layout/_macro/menu/menu-item.swig
  layout/_partials/header/sub-menu.swig
  source/css/_schemes/Pisces/_sub-menu.styl
Labels: Bugfix, Docs, Feature, Verified

#497 fix submenu when path name is same
  layout/_partials/breadcrumb.swig
  layout/_partials/header/sub-menu.swig
Labels: Need Review

#498 Fixed sidebar under Pisces / Gemini schemes for IE 11.
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/js/src/schemes/pisces.js
Labels: Bugfix, CSS

#500 Added `disable_baidu_tranformation` option.
  _config.yml
  layout/_partials/head/head.swig
Labels: Bugfix

#501 Fixed W3 validator errors.
  layout/_macro/sidebar.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_partials/search/swiftype.swig
  layout/_scripts/boostrap.swig
  layout/_scripts/commons.swig
  layout/_scripts/noscript.swig
  layout/_scripts/pages/post-details.swig
  layout/_scripts/schemes/gemini.swig
  layout/_scripts/schemes/pisces.swig
  layout/_scripts/vendors.swig
  layout/_third-party/analytics/application-insights.swig
  layout/_third-party/analytics/baidu-analytics.swig
  layout/_third-party/analytics/tencent-analytics.swig
  layout/_third-party/analytics/vkontakte-api.swig
  layout/_third-party/bookmark.swig
  layout/_third-party/comments/changyan.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/gitment.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/exturl.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/pangu.swig
  layout/_third-party/pdf.swig
  layout/_third-party/rating.swig
  layout/_third-party/scroll-cookie.swig
  layout/_third-party/search/localsearch.swig
Labels: Bugfix

#504 Fixed Disqus bug if in permalink exists symbol «'» .
  layout/_third-party/comments/disqus.swig
Labels: Bugfix

#506 Fixed Disqus URL. Again. A little bit hard.
  layout/_third-party/comments/disqus.swig
Labels: Bugfix

#507 Conditional import Han style.
  source/css/_common/components/third-party/han.styl
  source/css/_common/components/third-party/third-party.styl
Labels: Optimization

#509 Refactored post navigation styles.
  source/css/_common/components/post/post-nav.styl
Labels: Optimization

#518 Updated site link & small corrections.
  LICENSE.md
  docs/LICENSE.txt
Labels: Optimization

#520 Reorganize #274 Custom logo for Gemini & Pisces
  _config.yml
  layout/_partials/header/brand.swig
  source/css/_common/components/header/site-meta.styl
  source/css/_schemes/Muse/_logo.styl
  source/css/_schemes/Pisces/_brand.styl
  source/js/src/motion.js
  source/js/src/utils.js
Labels: Feature

#514 Fix inline code font-size mismatch within headers
  source/css/_common/scaffolding/base.styl
  source/css/_schemes/Gemini/index.styl
Labels: Bugfix, Need Review

#529 * Fix for metadata generation at index.
  layout/_macro/post.swig
Labels: Bugfix

#532 Fix #531, format code in _config.yml
  _config.yml
  source/css/_common/components/pages/archive.styl
  source/css/_common/components/post/post-reward.styl
Labels: Bugfix

#528 Add toc max_depth support
  _config.yml
  layout/_macro/sidebar.swig
Labels: Docs, Feature

#534 Fix #181 and #333
  _config.yml
  layout/_macro/post.swig
  layout/_scripts/vendors.swig
Labels: Bugfix

#538 Fix #537
  _config.yml
  source/css/_common/components/third-party/algolia-search.styl
Labels: Bugfix

#540 Fix localsearch wrong article url
  layout/_third-party/search/localsearch.swig
Labels: Bugfix

#541 Fix #271
  _config.yml
  layout/_third-party/analytics/application-insights.swig
  layout/_third-party/analytics/cnzz-analytics.swig
  layout/_third-party/analytics/facebook-sdk.swig
  layout/_third-party/analytics/google-analytics.swig
  layout/_third-party/analytics/growingio.swig
  layout/_third-party/analytics/tencent-mta.swig
  layout/_third-party/analytics/vkontakte-api.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/needsharebutton.swig
  layout/_third-party/rating.swig
  layout/_third-party/seo/baidu-push.swig
  layout/page.swig
Labels: Feature

#546 Fix #508
  _config.yml
  layout/_macro/menu/menu-item.swig
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/github-banner.swig
  layout/_partials/head/external-fonts.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_partials/post/post-related.swig
  layout/_partials/post/wechat-subscriber.swig
  layout/_partials/search/swiftype.swig
  layout/_partials/share/duoshuo_share.swig
  layout/_scripts/noscript.swig
  layout/_scripts/vendors.swig
  layout/_third-party/bookmark.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/gitment.swig
  layout/_third-party/math/index.swig
  layout/_third-party/math/katex.swig
  layout/_third-party/pangu.swig
  layout/_third-party/search/algolia-search/assets.swig
  layout/_third-party/search/localsearch.swig
  layout/post.swig
  scripts/tags/full-image.js
  source/css/_common/components/post/post-reward.styl
  source/js/src/utils.js
Labels: Bugfix

#554 Fix #553 New Feature: mhchem support
  _config.yml
  layout/_third-party/math/mathjax.swig
Labels: Docs, Feature

#550 Fix #48
  source/css/_common/outline/outline.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_variables/base.styl
  source/js/src/motion.js
  source/js/src/schemes/pisces.js
  source/js/src/utils.js
Labels: Bugfix, Feature
