Repository theme-next/hexo-theme-next, pull requests merged in 2018-02, with the labels that each got.

#136 Added BreadCrumbs feature.
  layout/_partials/breadcrumb.swig
  layout/_partials/page-header.swig
  layout/page.swig
  source/css/_common/components/pages/breadcrumb.styl
  source/css/_common/components/pages/pages.styl
Labels: Enhancement

#140 Added `include_raw` tag feature.
  scripts/tags/include-raw.js
Labels: Docs, Enhancement

#137 fix leancloud counter security bug
  _config.yml
  docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
  layout/_third-party/analytics/lean-analytics.swig
Labels: Discussion, Docs, Enhancement

#149 fix missing margin for h1
  source/css/_common/scaffolding/base.styl
Labels: Bug
