Repository theme-next/hexo-theme-next, pull requests merged in 2018-06, with the labels that each got.

#313 Merge branch 'ivan/feat-custom-lang' into dev
  .stickler.yml
  source/js/src/utils.js
Labels: Configurations

#326 Refactored JS files.
  layout/_partials/footer.swig
  scripts/helpers.js
  scripts/tags/button.js
  scripts/tags/center-quote.js
  scripts/tags/exturl.js
  scripts/tags/full-image.js
  scripts/tags/group-pictures.js
  scripts/tags/include-raw.js
  scripts/tags/label.js
  scripts/tags/lazy-image.js
  scripts/tags/note.js
  scripts/tags/tabs.js
  source/css/_common/components/tags/exturl.styl
  source/css/_common/components/tags/full-image.styl
  source/css/_variables/Pisces.styl
  source/css/_variables/base.styl
  source/js/src/affix.js
  source/js/src/algolia-search.js
  source/js/src/bootstrap.js
  source/js/src/exturl.js
  source/js/src/motion.js
  source/js/src/post-details.js
  source/js/src/schemes/pisces.js
  source/js/src/scroll-cookie.js
  source/js/src/scrollspy.js
  source/js/src/utils.js
Labels: Bugfix, Feature, Optimization

#332 Updated Docs.
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
Labels: Docs

#335 Add CDN examples for theme-next-three
  _config.yml
Labels: Docs
