Repository theme-next/hexo-theme-next, pull requests merged in 2018-04, with the labels that each got.

#210 Fix for default language if no `language` in Hexo config defined.
  languages/default.yml
Labels: Bugfix, Hexo, i18n

#214 Added `footer.powered.version` option to display Hexo version in footer.
  _config.yml
  layout/_partials/footer.swig
  scripts/helpers.js
Labels: Breaking Change, Feature

#213 Update guide for creating releases in CONTRIBUTING.MD
  .github/CONTRIBUTING.md
  docs/zh-CN/CONTRIBUTING.md
Labels: Docs

#221 Refactored header components.
  layout/_layout.swig
  layout/_macro/menu/menu-badge-1.swig
  layout/_macro/menu/menu-item.swig
  layout/_partials/header.swig
  layout/_partials/header/brand.swig
  layout/_partials/header/index.swig
  layout/_partials/header/menu.swig
  layout/_partials/header/sub-menu.swig
  layout/_partials/search.swig
  layout/_partials/search/index.swig
  scripts/helpers.js
Labels: Bugfix, Optimization

#208 [new feature] add post edit button
  _config.yml
  languages/en.yml
  languages/zh-CN.yml
  layout/_macro/post.swig
  source/css/_common/components/post/post-title.styl
Labels: Feature

#223 Add date_time_merge filed into post_meta
  _config.yml
  layout/_macro/post.swig
Labels: Feature

#229 Refactored menu items & badges.
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
  layout/_macro/menu/menu-badge-1.swig
  layout/_macro/menu/menu-badge-2.swig
  layout/_macro/menu/menu-badge.swig
  layout/_macro/menu/menu-item.swig
  layout/_partials/header/menu.swig
  source/css/_schemes/Pisces/_sub-menu.styl
Labels: Bugfix, Docs, Optimization

#228 [Optimization] Rewrite some code logic and method change for `post_meta.updated_at` option.
  _config.yml
  languages/en.yml
  layout/_macro/post.swig
  source/css/_common/components/post/post-meta.styl
Labels: Breaking Change, Bugfix, Feature, Optimization

#234 add copy codeblock button
  _config.yml
  languages/en.yml
  languages/zh-TW.yml
  layout/_layout.swig
  layout/_third-party/copy-code.swig
Labels: Feature

#235 New Crowdin translations
  languages/de.yml
  languages/fr.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: i18n

#238 fix css of copycode button
  layout/_third-party/copy-code.swig
Labels: Bugfix

#240 Added Hexo and NexT environment variables.
  .jshintrc
  _config.yml
  bower.json
  layout/_layout.swig
  layout/_partials/footer.swig
  layout/_partials/head/head.swig
  layout/_scripts/boostrap.swig
  layout/_scripts/commons.swig
  layout/_scripts/pages/post-details.swig
  layout/_scripts/schemes/gemini.swig
  layout/_scripts/schemes/pisces.swig
  layout/_third-party/exturl.swig
  layout/_third-party/scroll-cookie.swig
  layout/_third-party/search/algolia-search/assets.swig
  package.json
  scripts/helpers.js
Labels: Optimization

#250 Update readme's badges.
  README.md
Labels: Docs

#242 change copy-button position to absolute
  layout/_third-party/copy-code.swig
Labels: Bugfix

#252 New Crowdin translations
  languages/de.yml
  languages/fr.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: i18n

#262 fixed text font of the Mist scheme is smaller than other schemes on mobile phone
  source/css/_schemes/Mist/_posts-expanded.styl
Labels: Bugfix
