Repository theme-next/hexo-theme-next, pull requests merged in 2018-10, with the labels that each got.

#432 Fixed resize filter & affix & back to top for sidebar (#431).
  source/js/src/schemes/pisces.js
  source/js/src/utils.js
Labels: Bugfix

#433 Fix for `offset` option. [2]
  source/js/src/utils.js
Labels: Bugfix

#434 Fixes for b2t & variables refactoring.
  source/css/_common/components/back-to-top-sidebar.styl
  source/css/_schemes/Gemini/index.styl
Labels: Bugfix, CSS, Optimization

#439 Delete Bootcss settings and docs
  _config.yml
  docs/MATH.md
  docs/zh-CN/MATH.md
Labels: Docs

#354 Add growingio analytics
  _config.yml
  layout/_third-party/analytics/growingio.swig
  layout/_third-party/analytics/index.swig
Labels: Feature, Need Review

#443 Add Contributors list
  .all-contributorsrc
  README.md
  package.json
Labels: Docs

#456 Feat: Add sina weibo option to social block in sidebar settings
  _config.yml
Labels: Feature, Need Review

#441 Add options for canvas-nest
  _config.yml
  layout/_scripts/vendors.swig
Labels: Feature
