Repository theme-next/hexo-theme-next, pull requests merged in 2018-07, with the labels that each got.

#339 Custom sidebar width & content width for all schemes.
  _config.yml
  source/css/_common/outline/outline.styl
  source/css/_mixins/base.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_variables/Gemini.styl
  source/css/_variables/Pisces.styl
  source/css/_variables/base.styl
  source/js/src/motion.js
Labels: Breaking Change, Bugfix, Feature

#341 Replaced `&mdash;` with `&ndash;` for better visibility.
  layout/index.swig
Labels: Bugfix

#342 Removed HyperComments because for now only paid. =(
  _config.yml
  layout/_macro/post.swig
  layout/_partials/comments.swig
  layout/_third-party/comments/hypercomments.swig
  layout/_third-party/comments/index.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/comments/youyan.swig
Labels: 3rd party service, Breaking Change, Optimization

#343 Fixed NexT `package.json` path on Windows.
  scripts/helpers.js
Labels: Bugfix

#345 Update valine comment system version
  _config.yml
  layout/_macro/post.swig
  layout/_third-party/analytics/lean-analytics.swig
  layout/_third-party/comments/valine.swig
Labels: Feature

#302 Fix the post date display bug and Updated the post meta display
  layout/_macro/post.swig
Labels: Bugfix

#357 Refactor the share tools within post-widgets
  _config.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/share/jiathis.swig
  layout/post.swig
  source/css/_common/components/post/post-widgets.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/third-party/baidushare.styl
  source/css/_common/components/third-party/jiathis.styl
  source/css/_common/components/third-party/third-party.styl
Labels: Bugfix, Optimization

#358 Fixes indentation for `note` and `tabs` tags.
  scripts/tags/note.js
  scripts/tags/tabs.js
Labels: Bugfix

#360 Delete youyan comment
  _config.yml
  layout/_partials/comments.swig
  layout/_third-party/comments/index.swig
  layout/_third-party/comments/youyan.swig
Labels: 3rd party service
