Repository theme-next/hexo-theme-next, pull requests merged in 2019-06, with the labels that each got.

#890 Restore the previous selection for `copy_button`
  layout/_third-party/copy-code.swig
Labels: 🛠 Improvement

#704 Make Tabs flexible
  source/css/_common/components/tags/tabs.styl
Labels: CSS, 🛠 Improvement

#895 Add detailed description about RSS
  _config.yml
Labels: 📖 Docs

#891 Improve page rendering by deferring disqus loading
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/disqusjs.swig
Labels: 🛠 Improvement

#905 Correct the outdated version number of FontAwesome
  _config.yml
  layout/_partials/head/head.swig
Labels: 🛠 Improvement

#832 Force include source/lib/font-awesome/
  .gitignore
Labels: 🐞 Bug Fix

#903 Upgrade the internal jQuery to v3.4.1
  _config.yml
  bower.json
  layout/_scripts/vendors.swig
  source/lib/jquery/index.js
Labels: 🌀 External Change

#913 Fix word spelling
  _config.yml
Labels: v6.x, 🛠 Improvement

#916 Ignore leancloud visitor from localhost
  layout/_third-party/analytics/lean-analytics.swig
Labels: 🔌 3rd Party Service, 🛠 Improvement

#912 Remove Han support
  _config.yml
  layout/_macro/post.swig
  layout/_partials/head/head.swig
  layout/page.swig
  source/css/_common/components/third-party/han.styl
  source/css/_common/components/third-party/third-party.styl
Labels: 💥 Breaking Change

#907 Use hyphen instead of en dash
  layout/index.swig
Labels: 🛠 Improvement

#927 Remove unneeded leancloud-storage in `theme.vendors`
  _config.yml
Labels: 🌀 External Change, 🔌 3rd Party Service

#928 Remove unnecessary statements in swig templates
  layout/_macro/menu/menu-item.swig
  layout/_partials/search/algolia-search.swig
Labels: 🛠 Improvement

#934 Fix referer used by LiveRe on non-post pages
  layout/_third-party/comments/livere.swig
Labels: 🐞 Bug Fix, 🔌 3rd Party Service

#937 Refactoring post-meta-divider
  layout/_macro/post.swig
  source/css/_common/components/post/post-meta.styl
Labels: 🐞 Bug Fix, 🛠 Improvement

#939 Remove gitment support
  _config.yml
  layout/_macro/post.swig
  layout/_partials/comments.swig
  layout/_third-party/comments/gitment.swig
  layout/_third-party/comments/index.swig
  source/css/_common/components/third-party/gitment.styl
  source/css/_common/components/third-party/third-party.styl
Labels: 💥 Breaking Change

#938 Prune CSS about code highlight
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/post/post-expand.styl
Labels: CSS, 🛠 Improvement
