Repository theme-next/hexo-theme-next, pull requests merged in 2019-08, with the labels that each got.

#1041 Refactor lint / tests / bower
  .bowerrc
  .editorconfig
  .jshintrc
  bower.json
  gulpfile.coffee
  package.json
  source/js/exturl.js
  source/js/scrollspy.js
  test/.jshintrc
  test/helpers.js
  test/intern.js
Labels: 🛠 Improvement

#1003 Arrow function expression
  scripts/filters/comment/changyan.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/disqusjs.js
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/gitalk.js
  scripts/filters/comment/livere.js
  scripts/filters/comment/valine.js
  scripts/filters/comment/vkontakte.js
  scripts/filters/comment/warn.js
  scripts/filters/default-injects.js
  scripts/filters/exturl.js
  scripts/filters/lazyload.js
  scripts/helpers/engine.js
  scripts/helpers/font.js
  scripts/hexo-event.js
  scripts/injects.js
  scripts/tags/button.js
  scripts/tags/caniuse.js
  scripts/tags/full-image.js
  scripts/tags/include-raw.js
  source/js/utils.js
Labels: 🛠 Improvement

#1039 Fix affix bug
  source/js/schemes/pisces.js
Labels: 🐞 Bug Fix

#1042 Fix bugs caused by `this` and optimize the loading of cheerio
  scripts/filters/exturl.js
  scripts/filters/lazyload.js
  scripts/hexo-event.js
Labels: 🐞 Bug Fix

#1043 Reorganize the structure of `generateBefore`
  scripts/events/core.js
  scripts/events/lib/config.js
  scripts/events/lib/injects-point.js
  scripts/events/lib/injects.js
  scripts/filters/default-injects.js
Labels: 🛠 Improvement

#1044 Refactor inject style path
  scripts/events/lib/injects.js
  source/css/main.styl
Labels: 🐞 Bug Fix

#1045 Refactor custom pages
  _config.yml
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_scripts/pages/schedule.swig
  layout/_third-party/index.swig
  layout/_third-party/math/index.swig
  layout/page.swig
  layout/schedule.swig
  source/css/_common/components/pages/schedule.styl
Labels: 🛠 Improvement

#1047 Fix codeblock diff highlight bug
  source/css/_common/components/highlight/diff.styl
Labels: CSS, 🐞 Bug Fix

#1049 Refactor save_scroll
  _config.yml
  layout/_layout.swig
  layout/_partials/head/head.swig
  layout/_scripts/scroll-cookie.swig
  source/js/js.cookie.js
  source/js/next-boot.js
  source/js/scroll-cookie.js
  source/js/utils.js
Labels: ⏱ Performance, 🛠 Improvement

#1024 PJAX support
  _config.yml
  layout/_layout.swig
  layout/_macro/menu/menu-item.swig
  layout/_partials/analytics/busuanzi-counter.swig
  layout/_partials/analytics/cnzz-analytics.swig
  layout/_partials/analytics/tencent-analytics.swig
  layout/_partials/analytics/tencent-mta.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_partials/pjax.swig
  layout/_scripts/pages/schedule.swig
  layout/_scripts/vendors.swig
  layout/_third-party/analytics/application-insights.swig
  layout/_third-party/analytics/baidu-analytics.swig
  layout/_third-party/analytics/firestore.swig
  layout/_third-party/analytics/google-analytics.swig
  layout/_third-party/analytics/growingio.swig
  layout/_third-party/analytics/lean-analytics.swig
  layout/_third-party/baidu-push.swig
  layout/_third-party/bookmark.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/index.swig
  layout/_third-party/rating.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
  layout/_third-party/vkontakte-api.swig
  scripts/helpers/engine.js
  source/js/algolia-search.js
  source/js/exturl.js
  source/js/local-search.js
  source/js/motion.js
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: 🌟 New Feature

#1051 Need more cache 2
  layout/_layout.swig
  layout/_partials/header/index.swig
  layout/_partials/header/menu.swig
  layout/_scripts/index.swig
Labels: ⏱ Performance, 🛠 Improvement

#1053 Remove full-image tag
  scripts/tags/full-image.js
  source/css/_common/components/tags/full-image.styl
  source/css/_common/components/tags/tags.styl
Labels: ⭐ Feature

#1057 Fix issues caused by PJAX
  _config.yml
  layout/_third-party/comments/changyan.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
  scripts/helpers/engine.js
  source/js/utils.js
Labels: 🐞 Bug Fix

#1056 Improve the style of firebase analytics and post-meta
  _config.yml
  layout/_macro/post.swig
  layout/_partials/footer.swig
  layout/_third-party/analytics/firestore.swig
  layout/_third-party/analytics/lean-analytics.swig
  scripts/filters/comment/common.js
  source/css/_common/components/post/post-meta.styl
  source/css/_common/components/post/post-title.styl
Labels: Configurations, 🛠 Improvement

#1061 Show year devision in category or tag page
  layout/_macro/post-collapse.swig
  layout/archive.swig
  layout/category.swig
  layout/tag.swig
Labels: ⭐ Feature

#1062 Strange bug with symlinked `next` dir
  scripts/events/lib/config.js
Labels: Help Wanted, 🐞 Bug Fix

#1048 Add multi-comments
  _config.yml
  languages/en.yml
  layout/_partials/comments.swig
  layout/_partials/head/head.swig
  scripts/filters/comment/changyan.js
  scripts/filters/comment/common.js
  scripts/filters/comment/default-config.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/valine.js
  scripts/filters/comment/vkontakte.js
  scripts/filters/comment/warn.js
  source/css/_common/components/comments.styl
  source/css/_common/components/tags/tabs.styl
  source/css/_common/components/tags/tags.styl
  source/css/_schemes/Gemini/index.styl
  source/js/next-boot.js
  source/js/utils.js
Labels: 🌟 New Feature

#1075 Optimize the rendering of post
  layout/_macro/post.swig
  layout/_partials/post/post-copyright.swig
  layout/_partials/post/post-footer.swig
  layout/_partials/post/post-reward.swig
  layout/_partials/share/index.swig
  layout/_partials/share/likely.swig
Labels: 🛠 Improvement

#1076 Optimize the loading of exturl
  layout/_partials/head/head.swig
  layout/_scripts/exturl.swig
  layout/_scripts/index.swig
  scripts/filters/minify.js
  source/js/exturl.js
  source/js/next-boot.js
  source/js/utils.js
Labels: ⏱ Performance, 🛠 Improvement

#1079 New Crowdin translations
  languages/de.yml
  languages/es.yml
  languages/fa.yml
  languages/fr.yml
  languages/hu.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/uk.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: 🌍 i18n

#1080 Refactor auto excerpt
  _config.yml
  layout/_macro/post.swig
  scripts/filters/excerpt.js
Labels: 🛠 Improvement

#1081 Refactor vendors
  _config.yml
  layout/_partials/head/head.swig
  layout/_partials/share/likely.swig
  layout/_partials/share/needsharebutton.swig
  layout/_scripts/three.swig
  layout/_scripts/vendors.swig
  layout/_third-party/bookmark.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/math/index.swig
  layout/_third-party/math/katex.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/quicklink.swig
  layout/_third-party/search/algolia-search.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
Labels: 💥 Breaking Change, 🛠 Improvement

#1089 Use Pure JavaScript instead of jQuery [0]
  _config.yml
  layout/_partials/pjax.swig
  layout/_third-party/analytics/firestore.swig
  layout/_third-party/analytics/lean-analytics.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/next-boot.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: ⏱ Performance, 🛠 Improvement

#1090 Use arrow function in front-end
  layout/_partials/comments.swig
  layout/_partials/pjax.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/facebook-sdk.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
  layout/_third-party/vkontakte-api.swig
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/motion.js
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: 🛠 Improvement

#1091 Use pure JavaScript instead of jQuery [1]
  layout/_partials/head/head.swig
  layout/_partials/search/algolia-search.swig
  layout/_partials/search/localsearch.swig
  source/css/_common/components/third-party/algolia-search.styl
  source/css/_common/components/third-party/localsearch.styl
  source/css/_common/components/third-party/search.styl
  source/css/_common/components/third-party/third-party.styl
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/utils.js
Labels: 🛠 Improvement

#1093 Fix leancloud counter bug
  layout/_third-party/analytics/lean-analytics.swig
Labels: 🐞 Bug Fix

#1092 Use pure JavaScript instead of jQuery [2]
  layout/_partials/search/localsearch.swig
  layout/_scripts/schemes/pisces.swig
  layout/_third-party/analytics/lean-analytics.swig
  layout/_third-party/vkontakte-api.swig
  scripts/filters/minify.js
  source/css/_common/scaffolding/helpers.styl
  source/js/affix.js
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/motion.js
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: 🛠 Improvement

#1096 Add next_js helper
  layout/_scripts/commons.swig
  layout/_scripts/next-boot.swig
  layout/_scripts/pages/post-details.swig
  layout/_scripts/schemes/muse.swig
  layout/_scripts/schemes/pisces.swig
  layout/_third-party/search/algolia-search.swig
  layout/_third-party/search/localsearch.swig
  scripts/helpers/next-js.js
Labels: 🛠 Improvement

#1098 Add next_inject helper
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/footer.swig
  layout/_partials/header/index.swig
  scripts/helpers/next-inject.js
Labels: 🛠 Improvement

#1099 Remove post type quote & picture
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  source/css/_common/components/post/post-type.styl
  source/css/_common/components/post/post.styl
Labels: Configurations, ⭐ Feature

#1100 Refactor reading-progress
  _config.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_scripts/vendors.swig
  source/css/_common/components/components.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/reading-progress.styl
  source/js/local-search.js
  source/js/next-boot.js
  source/js/utils.js
Labels: ⭐ Feature

#1102 Use insertAdjacentHTML instead of appendChild
  source/js/local-search.js
Labels: 🐞 Bug Fix

#1101 Fix space after comment count
  scripts/filters/comment/changyan.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/valine.js
Labels: 🐞 Bug Fix

#1105 New helper next-vendors
  _config.yml
  layout/_partials/head/head.swig
  layout/_partials/share/needsharebutton.swig
  layout/_scripts/three.swig
  layout/_scripts/vendors.swig
  layout/_third-party/bookmark.swig
  layout/_third-party/quicklink.swig
  layout/_third-party/search/algolia-search.swig
  scripts/helpers/next-vendors.js
Labels: 🛠 Improvement

#1109 Use pure JavaScript instead of jQuery [3]
  layout/_layout.swig
  layout/_macro/sidebar.swig
  layout/_third-party/comments/disqus.swig
  source/css/_common/components/back-to-top-sidebar.styl
  source/css/_common/components/back-to-top.styl
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/utils.js
Labels: 🛠 Improvement

#1104 Extract all share systems to plugins
  _config.yml
  layout/_layout.swig
  layout/_partials/head/head.swig
  layout/_partials/post/post-footer.swig
  layout/_partials/share.swig
  layout/_partials/share/add-this.swig
  layout/_partials/share/index.swig
  layout/_partials/share/likely.swig
  layout/_partials/share/needsharebutton.swig
  source/css/_common/components/post/post-widgets.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/third-party/needsharebutton.styl
  source/css/_common/components/third-party/third-party.styl
Labels: 💥 Breaking Change

#1106 Extract bookmark / save_scroll to plugins
  _config.yml
  layout/_layout.swig
  layout/_partials/head/head.swig
  layout/_partials/pjax.swig
  layout/_scripts/commons.swig
  layout/_scripts/index.swig
  layout/_scripts/next-boot.swig
  layout/_third-party/bookmark.swig
  layout/_third-party/index.swig
  scripts/filters/minify.js
  source/css/_common/components/header/bookmark.styl
  source/css/_common/components/header/header.styl
  source/js/bookmark.js
  source/js/next-boot.js
Labels: ⭐ Feature

#1111 Fix PJAX refresh bugs when search / fancybox enabled
  layout/_partials/pjax.swig
  layout/_partials/search/algolia-search.swig
  layout/_partials/search/index.swig
  layout/_partials/search/localsearch.swig
  source/css/_common/components/third-party/search.styl
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/utils.js
Labels: 🐞 Bug Fix

#1112 Add color option for bookmark
  _config.yml
  layout/_layout.swig
  source/css/_common/components/header/bookmark.styl
Labels: CSS, ⭐ Feature

#1113 Make sidebar toc & PJAX loading faster
  languages/en.yml
  layout/_layout.swig
  layout/_macro/sidebar.swig
  layout/_partials/analytics/firestore.swig
  layout/_partials/analytics/index.swig
  layout/_partials/analytics/lean-analytics.swig
  layout/_partials/share.swig
  layout/_partials/widgets.swig
  layout/_scripts/pages/post-details.swig
  layout/_scripts/pjax.swig
  layout/_third-party/analytics/analytics-with-jquery.swig
  layout/_third-party/index.swig
  layout/_third-party/quicklink.swig
  source/css/_common/components/sidebar/sidebar-toc.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_schemes/Muse/sidebar/_sidebar.styl
  source/css/_schemes/Pisces/_layout.styl
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/scrollspy.js
  source/js/utils.js
Labels: PJAX, ⏱ Performance, 🛠 Improvement

#1117 New Crowdin translations
  languages/de.yml
  languages/es.yml
  languages/fa.yml
  languages/fr.yml
  languages/hu.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/uk.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: 🌍 i18n

#1119 Refactor links-of-blogroll-item
  _config.yml
  layout/_partials/sidebar/site-overview.swig
  source/css/_common/components/sidebar/sidebar-blogroll.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Mist/outline/outline.styl
  source/css/_schemes/Muse/_sidebar.styl
  source/css/_schemes/Muse/index.styl
  source/css/_schemes/Muse/sidebar/sidebar-blogroll.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: 🛠 Improvement

#1116 Use pure JavaScript instead of jQuery [4]
  layout/_macro/sidebar.swig
  layout/_partials/header/brand.swig
  layout/_scripts/pjax.swig
  source/js/local-search.js
  source/js/motion.js
  source/js/schemes/muse.js
Labels: ⏱ Performance, 🛠 Improvement

#1121 Expand beian options for users in mainland China
  _config.yml
  layout/_partials/footer.swig
Labels: ⭐ Feature

#1123 Use pure JavaScript instead of jQuery [5]
  layout/_layout.swig
  layout/_macro/sidebar.swig
  layout/_scripts/pages/post-details.swig
  layout/page.swig
  layout/post.swig
  scripts/tags/caniuse.js
  source/css/_common/components/post/post-expand.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/mobile.styl
  source/js/bookmark.js
  source/js/next-boot.js
  source/js/post-details.js
  source/js/utils.js
Labels: ⏱ Performance, 🛠 Improvement

#1124 Make CSS selectors and dimensional calculations more robust
  layout/_layout.swig
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/footer.swig
  layout/_partials/sidebar/site-overview.swig
  layout/_partials/widgets.swig
  layout/archive.swig
  layout/category.swig
  layout/index.swig
  layout/page.swig
  layout/post.swig
  layout/tag.swig
  scripts/tags/caniuse.js
  source/css/_common/components/header/github-banner.styl
  source/css/_common/components/highlight/copy-code.styl
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-expand.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_common/components/tags/group-pictures.styl
  source/css/_common/scaffolding/mobile.styl
  source/css/_common/scaffolding/tables.styl
  source/css/_schemes/Mist/_posts-expand.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Muse/_sidebar.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/next-boot.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: CSS, 🛠 Improvement

#1125 IntersectionObserver about TOC
  source/js/utils.js
Labels: 🐞 Bug Fix

#1130 Reimplement Bootstrap Affix
  layout/_macro/sidebar.swig
  source/js/schemes/pisces.js
Labels: 🛠 Improvement

#1129 Use pure JavaScript instead of jQuery [6]
  source/js/next-boot.js
  source/js/utils.js
Labels: 🛠 Improvement

#1128 Refactor sidebar motion
  layout/_scripts/noscript.swig
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_common/scaffolding/helpers.styl
  source/css/_schemes/Muse/_sidebar.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/css/_variables/Mist.styl
  source/css/_variables/Muse.styl
  source/css/_variables/base.styl
  source/js/next-boot.js
  source/js/schemes/muse.js
  source/js/utils.js
Labels: 🛠 Improvement

#1134 Use pure JavaScript instead of jQuery [7]
  layout/_layout.swig
  layout/_scripts/index.swig
  layout/_scripts/pjax.swig
  layout/_scripts/three.swig
  source/js/next-boot.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: 🛠 Improvement

#1136 Add order for theme_inject
  _config.yml
  scripts/events/lib/injects.js
  scripts/filters/comment/changyan.js
  scripts/filters/comment/default-config.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/disqusjs.js
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/gitalk.js
  scripts/filters/comment/livere.js
  scripts/filters/comment/valine.js
  scripts/filters/comment/vkontakte.js
Labels: 💥 Breaking Change

#1135 Use pure JavaScript instead of jQuery [8]
  .gitignore
  _config.yml
  layout/_macro/sidebar.swig
  layout/_partials/head/head.swig
  layout/_scripts/vendors.swig
  scripts/filters/minify.js
  source/css/_common/components/footer/footer.styl
  source/css/_common/components/header/site-nav.styl
  source/css/_common/components/post/post-eof.styl
  source/css/_common/components/third-party/search.styl
  source/css/_common/scaffolding/helpers.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_menu.styl
  source/js/bookmark.js
  source/js/local-search.js
  source/js/motion.js
  source/js/next-boot.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
  source/lib/anime.min.js
  source/lib/jquery/index.js
Labels: 💥 Breaking Change

#976 Revert #42, #87
  layout/_partials/sidebar/site-overview.swig
  layout/page.swig
Labels: ⏱ Performance, 🛠 Improvement
