Repository theme-next/hexo-theme-next, pull requests merged in 2019-04, with the labels that each got.

#774 Install Mergeable bot which totally replaced WIP bot and have more settings
  .github/mergeable.yml
Labels: 3rd Party Service, Improvement

#779 Change Feedback section
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
Labels: Docs, v6.x

#778 Change Stale bot labels
  .github/stale.yml
Labels: 3rd Party Service, Improvement

#773 Install Weekly Digest bot
  .github/weekly-digest.yml
Labels: 3rd Party Service, Improvement

#782 Install Lock bot
  .github/lock.yml
Labels: 3rd Party Service, Improvement

#775 Install Auto Assign bot
  .github/auto_assign.yml
Labels: 3rd Party Service, Improvement

#776 Install Top Issues bot
  .github/topissuebot.yml
Labels: 3rd Party Service, Improvement

#777 Install ESLint Diable Watcher bot
  .github/eslint-disable-bot.yml
Labels: 3rd Party Service, Improvement

#781 Install Welcome, Request Info and Sentiment bots
  .github/config.yml
Labels: 3rd Party Service, Improvement

#784 Fix Top Issue Label
  .github/topissuebot.yml
Labels: 3rd Party Service, Improvement

#780 Install Support bot
  .github/support.yml
Labels: 3rd Party Service, Improvement

#787 Change lockLabel
  .github/lock.yml
Labels: 3rd Party Service, Improvement

#792 Improve bots configs
  .github/auto_assign.yml
  .github/config.yml
  .github/eslint-disable-bot.yml
  .github/mergeable.yml
  .github/release-drafter.yml
  .github/topissuebot.yml
  .github/weekly-digest.yml
Labels: 3rd Party Service, Improvement

#794 Bug Fix: PDF won't display in particular situation
  source/css/_common/components/tags/pdf.styl
Labels: Bug Fix

#795 Disable add Assigners in Auto Assign bot
  .github/auto_assign.yml
Labels: 3rd Party Service, Improvement

#797 Reduce reviewers for remove scrolling in PR's
  .github/auto_assign.yml
Labels: 3rd Party Service, Improvement

#801 Spanish translation
  languages/es.yml
Labels: i18n

#803 CSS bug in Codeblock if string longer than viewport
  source/css/_common/scaffolding/tables.styl
  source/js/utils.js
Labels: Bug Fix, CSS

#806 New Crowdin translations
  languages/es.yml
Labels: i18n

#808 Fix wrong sidebar style on mobile
  source/css/_common/components/back-to-top-sidebar.styl
  source/css/_common/components/back-to-top.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_mixins/base.styl
  source/css/_variables/base.styl
Labels: Bug Fix, CSS

#818 Improve French translation
  languages/fr.yml
Labels: i18n

#819 Improve French translation
  languages/fr.yml
Labels: i18n

#817 List items appeared correctly in mobile with `mobile_layout_economy` option
  source/css/_common/scaffolding/mobile.styl
Labels: Bug Fix, CSS, v6.x

#827 Update IPC url
  _config.yml
  layout/_partials/footer.swig
Labels: Improvement

#828 Wrong padding with `mobile_layout_economy` option enabled in mobile
  source/css/_common/scaffolding/mobile.styl
Labels: Bug Fix, CSS

#833 Fix typo in config comments
  _config.yml
Labels: Improvement, v6.x

#849 Fix alignments for several elements with `mobile_layout_economy` option
  source/css/_common/scaffolding/mobile.styl
Labels: Bug Fix, CSS

#853 Persian translation
  languages/fa.yml
Labels: i18n
