Repository theme-next/hexo-theme-next, pull requests merged in 2019-07, with the labels that each got.

#929 Fix image line number calculation error, the picture can not be fully loaded
  scripts/tags/group-pictures.js
Labels: 🛠 Improvement

#931 Fix Group Pictures layout
  source/css/_common/components/tags/group-pictures.styl
Labels: CSS, 🛠 Improvement

#946 Update reading_progress vendor version number
  _config.yml
Labels: 🌀 External Change

#944 Rebuild ALL-CONTRIBUTORS-LIST in README.md
  .all-contributorsrc
  README.md
Labels: 🛠 Improvement

#952 Allow setting sidebar position to left or right in scheme Muse & Mist
  _config.yml
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Mist/sidebar/sidebar-blogroll.styl
  source/css/_schemes/Muse/index.styl
  source/css/_schemes/Muse/sidebar/_sidebar.styl
  source/js/motion.js
  source/js/schemes/muse.js
Labels: CSS, ⭐ Feature, 🎯 Roadmap, 💥 Breaking Change

#953 Refactoring CSS: Using Pseudo-elements selector
  source/css/_common/components/pages/breadcrumb.styl
  source/css/_common/components/pages/categories.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/rainbow.styl
  source/css/_common/components/sidebar/sidebar-author-links.styl
  source/css/_common/components/tags/note.styl
  source/css/_common/components/tags/tabs.styl
  source/css/_common/components/third-party/gitalk.styl
  source/css/_common/scaffolding/mobile.styl
  source/css/_mixins/base.styl
  source/css/_schemes/Mist/_posts-expanded.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Pisces/_menu.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/css/_schemes/Pisces/_sub-menu.styl
Labels: CSS, 🛠 Improvement

#957 Make lazyload working again
  _config.yml
  layout/_scripts/vendors.swig
  scripts/filters/lazyload.js
  scripts/tags/exturl.js
  scripts/tags/full-image.js
  source/images/loading.gif
  source/images/placeholder.gif
  source/images/searchicon.png
  source/js/utils.js
Labels: 🐞 Bug Fix, 🛠 Improvement

#868 Add new filter type `theme_inject`
  _config.yml
  layout/_custom/head.swig
  layout/_custom/header.swig
  layout/_custom/sidebar.swig
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/footer.swig
  layout/_partials/head/head.swig
  layout/_partials/header/index.swig
  scripts/filters/default-injects.js
  scripts/injects-point.js
  scripts/injects.js
  scripts/merge-configs.js
  source/css/_custom/custom.styl
  source/css/_mixins/custom.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_variables/custom.styl
  source/css/main.styl
Labels: 🌟 New Feature, 💥 Breaking Change

#961 Fix TypeError: Cannot read property 'head' of null
  scripts/filters/default-injects.js
Labels: 🐞 Bug Fix

#935 Allow delayed loading of three.js
  _config.yml
  layout/_layout.swig
  layout/_scripts/three.swig
  layout/_scripts/vendors.swig
Labels: 🛠 Improvement

#959 Update docs in `_config.yml`
  _config.yml
Labels: 📖 Docs

#951 Load velocity only if motion is enabled
  layout/_scripts/commons.swig
  layout/_scripts/next-boot.swig
  layout/_scripts/vendors.swig
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/utils.js
Labels: 🌀 External Change, 🎯 Roadmap, 💥 Breaking Change

#964 Refactor sidebar-dimmer
  _config.yml
  layout/_macro/sidebar.swig
  source/css/_common/components/sidebar/sidebar-dimmer.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/js/schemes/muse.js
Labels: 💥 Breaking Change, 🛠 Improvement

#947 Create Awesome list
  .all-contributorsrc
  README.md
  docs/ALGOLIA-SEARCH.md
  docs/AUTHORS.md
  docs/ru/README.md
  docs/zh-CN/CODE_OF_CONDUCT.md
  docs/zh-CN/CONTRIBUTING.md
  docs/zh-CN/README.md
Labels: 📖 Docs

#954 Avoid recalculating the number of tags and categories
  layout/_macro/menu/menu-badge.swig
  layout/_macro/sidebar.swig
  layout/page.swig
  scripts/merge-configs.js
Labels: Performance, 🛠 Improvement

#966 Update devDependencies
  gulpfile.coffee
  package.json
Labels: 🛠 Improvement

#967 Remove baidushare
  _config.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/share/baidushare.swig
  source/css/_common/components/post/post.styl
Labels: 💥 Breaking Change, 🔌 3rd Party Service

#970 Use Object.assign instead of lodash merge
  .gitattributes
  scripts/merge-configs.js
  scripts/merge.js
Labels: 🛠 Improvement

#965 Refactor several components in `_config.yml`
  _config.yml
  layout/_partials/head/head.swig
  layout/_partials/header/brand.swig
  layout/_scripts/vendors.swig
  source/css/_common/components/highlight/diff.styl
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/highlight/theme.styl
  source/css/_common/components/sidebar/sidebar-author.styl
Labels: 💥 Breaking Change, 🛠 Improvement

#971 Cache sidebar site-overview
  layout/_layout.swig
  layout/_macro/sidebar.swig
  layout/_partials/head/head.swig
  layout/_partials/sidebar/site-overview.swig
Labels: Performance, 🛠 Improvement

#977 Disable selection for highlight meta
  source/css/_common/components/highlight/copy-code.styl
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/sidebar/sidebar-author.styl
  source/css/_mixins/base.styl
Labels: CSS, ⭐ Feature

#978 Update docs
  docs/LEANCLOUD-COUNTER-SECURITY.md
  docs/UPDATE-FROM-5.1.X.md
  docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
  docs/zh-CN/UPDATE-FROM-5.1.X.md
Labels: 📖 Docs

#984 Add new tag caniuse
  _config.yml
  layout/_layout.swig
  layout/_third-party/caniuse.swig
  scripts/tags/caniuse.js
Labels: 🌟 New Feature, 🔌 3rd Party Service

#985 Refactor layout
  layout/_layout.swig
  layout/_third-party/analytics/index.swig
  layout/_third-party/chat/chatra.swig
  layout/_third-party/chat/index.swig
  layout/_third-party/chat/tidio.swig
  layout/_third-party/tags/caniuse.swig
  layout/_third-party/tags/index.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
Labels: 🛠 Improvement

#989 Refactor caniuse
  _config.yml
  layout/_third-party/tags/caniuse.swig
  scripts/tags/caniuse.js
Labels: 🛠 Improvement

#987 Add medium-zoom support
  _config.yml
  layout/_partials/head/head.swig
  layout/_scripts/vendors.swig
  source/js/next-boot.js
  source/js/utils.js
Labels: 🌟 New Feature

#990 Optimize the loading of next-boot.js and some 3rd-party plugins
  _config.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/head/head.swig
  layout/_partials/share/add-this.swig
  layout/_partials/share/needsharebutton.swig
  layout/_scripts/vendors.swig
  layout/_third-party/index.swig
  layout/_third-party/pangu.swig
  source/css/_common/components/third-party/needsharebutton.styl
  source/css/_common/components/third-party/third-party.styl
  source/js/next-boot.js
  source/js/utils.js
Labels: 🛠 Improvement

#995 Remove fastclick support
  _config.yml
  layout/_partials/head/head.swig
  layout/_scripts/vendors.swig
  source/js/next-boot.js
Labels: 💥 Breaking Change, 🔌 3rd Party Service

#997 Create `page settings` part in `_config.yml`
  _config.yml
Labels: 🛠 Improvement

#1004 Fix list rendering problem when the list item contains mathjax formulae
  layout/_third-party/math/mathjax.swig
Labels: 🐞 Bug Fix

#1002 Console reminder if new version released
  _config.yml
  scripts/merge-configs.js
Labels: 🌟 New Feature, 🎯 Roadmap

#1005 Remove all hardcoded font sizes
  _config.yml
  source/css/_common/components/footer/footer.styl
  source/css/_common/components/header/menu.styl
  source/css/_common/components/header/site-meta.styl
  source/css/_common/components/highlight/copy-code.styl
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/pages/archive.styl
  source/css/_common/components/pages/breadcrumb.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-copyright.styl
  source/css/_common/components/post/post-meta.styl
  source/css/_common/components/post/post-nav.styl
  source/css/_common/components/post/post-reward.styl
  source/css/_common/components/post/post-tags.styl
  source/css/_common/components/post/post-title.styl
  source/css/_common/components/post/post-widgets.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/sidebar/sidebar-author-links.styl
  source/css/_common/components/sidebar/sidebar-blogroll.styl
  source/css/_common/components/sidebar/sidebar-button.styl
  source/css/_common/components/sidebar/sidebar-nav.styl
  source/css/_common/components/sidebar/sidebar-toc.styl
  source/css/_common/components/third-party/related-posts.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/helpers.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_header.styl
  source/css/_schemes/Mist/_posts-expanded.styl
  source/css/_schemes/Muse/_logo.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/css/_variables/Gemini.styl
  source/css/_variables/Mist.styl
  source/css/_variables/Pisces.styl
  source/css/_variables/base.styl
  source/css/main.styl
Labels: CSS, 🎯 Roadmap, 🛠 Improvement

#1001 Update docs
  docs/DATA-FILES.md
  docs/INSTALLATION.md
  docs/LEANCLOUD-COUNTER-SECURITY.md
  docs/ru/DATA-FILES.md
  docs/zh-CN/CONTRIBUTING.md
  docs/zh-CN/DATA-FILES.md
  docs/zh-CN/INSTALLATION.md
  docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
  docs/zh-CN/UPDATE-FROM-5.1.X.md
Labels: 📖 Docs

#991 Remove unnecessary files after hexo generate
  _config.yml
  scripts/filters/minify.js
Labels: 🛠 Improvement

#1007 Fix site title's external font family bug
  layout/_partials/head/external-fonts.swig
Labels: 🐞 Bug Fix

#1011 Make external google font better
  layout/_partials/head/external-fonts.swig
Labels: 🛠 Improvement

#1014 Refactor Muse menu on mobile
  source/css/_common/components/header/site-nav.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Muse/_layout.styl
  source/css/_schemes/Muse/_menu.styl
  source/css/_schemes/Pisces/_menu.styl
Labels: CSS, 🛠 Improvement

#998 Refactor comments using theme_inject
  layout/_macro/post.swig
  layout/_partials/comments.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/index.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/index.swig
  layout/index.swig
  layout/post.swig
  scripts/filters/comment/changyan.js
  scripts/filters/comment/common.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/disqusjs.js
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/gitalk.js
  scripts/filters/comment/livere.js
  scripts/filters/comment/valine.js
  scripts/filters/comment/vkontakte.js
  scripts/filters/comment/warn.js
  scripts/injects-point.js
Labels: 🛠 Improvement

#1013 Optimize stylesheet
  source/css/_common/components/back-to-top.styl
  source/css/_common/components/comments.styl
  source/css/_common/components/highlight/copy-code.styl
  source/css/_common/components/pages/pages.styl
  source/css/_common/components/pages/post-detail.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_common/scaffolding/base.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Muse/_menu.styl
  source/css/_schemes/Pisces/_menu.styl
Labels: CSS, 🛠 Improvement

#1015 Fix a bug when `theme.font` has empty family value
  layout/_partials/head/external-fonts.swig
Labels: 🐞 Bug Fix

#1012 Refactor search services
  _config.yml
  gulpfile.coffee
  layout/_partials/head/head.swig
  layout/_partials/header/menu.swig
  layout/_partials/search/index.swig
  layout/_third-party/search/algolia-search.swig
  layout/_third-party/search/index.swig
  layout/_third-party/search/localsearch.swig
  layout/_third-party/search/swiftype.swig
  scripts/filters/minify.js
  source/css/_schemes/Mist/_search.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Muse/_search.styl
  source/css/_schemes/Muse/index.styl
  source/css/_schemes/Pisces/_brand.styl
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/next-boot.js
  source/js/utils.js
Labels: ⭐ Feature, 🛠 Improvement

#1019 Obey ESLint rules
  scripts/injects.js
  scripts/merge-configs.js
  source/js/js.cookie.js
  source/js/local-search.js
  source/js/schemes/muse.js
  source/js/utils.js
Labels: 🛠 Improvement

#1031 New helper next_font
  layout/_partials/head/external-fonts.swig
  layout/_partials/head/head.swig
  scripts/helpers/font.js
Labels: 🛠 Improvement

#1023 Drop IE support
  layout/_scripts/vendors.swig
  layout/_third-party/analytics/lean-analytics.swig
  source/js/algolia-search.js
  source/js/local-search.js
  source/js/next-boot.js
  source/js/scrollspy.js
  source/js/utils.js
Labels: ⭐ Feature

#1022 Refactor share & analytics
  _config.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/analytics/busuanzi-counter.swig
  layout/_partials/analytics/cnzz-analytics.swig
  layout/_partials/analytics/index.swig
  layout/_partials/analytics/tencent-analytics.swig
  layout/_partials/analytics/tencent-mta.swig
  layout/_partials/head/head.swig
  layout/_partials/share/add-this.swig
  layout/_partials/share/index.swig
  layout/_partials/share/likely.swig
  layout/_partials/share/needsharebutton.swig
  layout/_scripts/vendors.swig
  layout/_third-party/analytics/firestore.swig
  layout/_third-party/analytics/index.swig
  layout/_third-party/facebook-sdk.swig
  layout/_third-party/index.swig
  layout/_third-party/vkontakte-api.swig
  source/css/_common/components/post/post-widgets.styl
  source/css/_common/components/third-party/needsharebutton.styl
Labels: 🛠 Improvement

#1032 Use HTML5 syntax instead of XHTML
  layout/_macro/post.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_partials/header/brand.swig
  layout/_partials/post/post-related.swig
  layout/_partials/post/reward.swig
  layout/_partials/post/wechat-subscriber.swig
  layout/_partials/sidebar/site-overview.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/math/katex.swig
  layout/_third-party/search/algolia-search.swig
Labels: 🛠 Improvement

#1034 Update docs in _config.yml
  _config.yml
Labels: 📖 Docs

#1036 Update release-drafter exclude-labels
  .github/release-drafter.yml
Labels: Skip Release

#1035 Configure JSHint
  .jshintrc
  package.json
  source/js/exturl.js
  source/js/local-search.js
Labels: 🛠 Improvement

#1033 Revert using one line macro
  source/css/_common/components/back-to-top-sidebar.styl
  source/css/_common/components/buttons.styl
  source/css/_common/components/header/menu.styl
  source/css/_common/components/header/site-nav.styl
  source/css/_common/components/pages/archive.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-eof.styl
  source/css/_common/components/post/post-meta.styl
  source/css/_common/components/post/post-nav.styl
  source/css/_common/components/post/post-reading_progress.styl
  source/css/_common/components/post/post-type.styl
  source/css/_common/components/rainbow.styl
  source/css/_common/components/sidebar/sidebar-author-links.styl
  source/css/_common/components/sidebar/sidebar-author.styl
  source/css/_common/components/sidebar/sidebar-dimmer.styl
  source/css/_common/components/sidebar/sidebar-toc.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_common/components/sidebar/site-state.styl
  source/css/_common/components/tags/blockquote-center.styl
  source/css/_common/components/tags/tabs.styl
  source/css/_common/components/third-party/algolia-search.styl
  source/css/_common/components/third-party/related-posts.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/helpers.styl
  source/css/_mixins/base.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_header.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Muse/_layout.styl
  source/css/_schemes/Muse/_menu.styl
  source/css/_schemes/Pisces/_brand.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_menu.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: CSS, 🛠 Improvement

#1006 Use em instead of px as the font size unit
  _config.yml
  source/css/_common/components/highlight/copy-code.styl
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/pages/archive.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-expand.styl
  source/css/_common/components/post/post-meta.styl
  source/css/_common/components/post/post-reward.styl
  source/css/_common/components/post/post-title.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/tags/note.styl
  source/css/_common/components/third-party/localsearch.styl
  source/css/_common/scaffolding/base.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_posts-expanded.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/css/_variables/Gemini.styl
  source/css/_variables/base.styl
Labels: CSS, 🎯 Roadmap, 💥 Breaking Change, 🛠 Improvement
