Repository theme-next/hexo-theme-next, pull requests merged in 2019-12, with the labels that each got.

#1299 Drop cheerio
  scripts/filters/post.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: 🎯 Roadmap, 🛠 Improvement

#1152 Make lazyload & PJAX available for all comment systems
  _config.yml
  layout/_partials/comments.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_third-party/comments/changyan.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/comments/valine.swig
  source/js/motion.js
  source/js/utils.js
Labels: 💥 Breaking Change

#1305 Use IntersectionObserver to lazyload comments
  layout/_third-party/comments/changyan.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/comments/valine.swig
  scripts/filters/comment/changyan.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/disqusjs.js
  scripts/filters/comment/livere.js
  scripts/filters/comment/valine.js
  source/js/utils.js
Labels: 🛠 Improvement

#1326 Fix Gitalk distractionFreeMode invalid bug
  layout/_third-party/comments/gitalk.swig
Labels: 🐞 Bug Fix
