Repository theme-next/hexo-theme-next, pull requests merged in 2019-02, with the labels that each got.

#595 two bugs . The one is the tip of comments-number,the anther is that plugin hexo-all-minifier changs the 'QR' to ' qr' so that the reward button not to ues.
  layout/_macro/post.swig
  layout/_partials/post/reward.swig
Labels: Bugfix

#565 Remove tinysou and duoshuo_share
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/header/menu.swig
  layout/_partials/search/algolia-search.swig
  layout/_partials/search/index.swig
  layout/_partials/search/tinysou.swig
  layout/_partials/share/add-this.swig
  layout/_partials/share/duoshuo_share.swig
  layout/_third-party/analytics/growingio.swig
  layout/_third-party/baidu-push.swig
  layout/_third-party/search/algolia-search.swig
  layout/_third-party/search/index.swig
  layout/_third-party/search/tinysou.swig
Labels: Optimization

#598 fix(markdown): make table scrollable
  source/css/_common/scaffolding/tables.styl
  source/js/src/utils.js
Labels: Bugfix

#602 Fix #601 Ordered list nested in unordered list became unordered
  source/css/_common/components/post/post-expand.styl
  source/css/_common/components/post/post-gallery.styl
  source/css/_common/components/post/post-meta.styl
Labels: Bugfix

#599 Fix #594: External links didn't get replaced in index page
  layout/_partials/post/wechat-subscriber.swig
  layout/_partials/search/index.swig
  layout/_third-party/analytics/lean-analytics.swig
  layout/_third-party/baidu-push.swig
  scripts/filters/exturl.js
  scripts/helpers/next-url.js
Labels: Bugfix

#618 FIX #617 add localhost filter for google analytics
  _config.yml
  layout/_third-party/analytics/google-analytics.swig
Labels: Feature

#607 Feature: Close sidebar when click any blank part (#606)
  _config.yml
  layout/_macro/sidebar.swig
  source/css/_common/components/sidebar/sidebar-dimmer.styl
  source/css/_common/components/sidebar/sidebar.styl
Labels: Feature

#612 Feat: Add quicklink support
  _config.yml
  layout/_layout.swig
  layout/_third-party/quicklink.swig
Labels: Feature

#603 Optimize the displaying of fancybox, mathjax and schedule
  _config.yml
  layout/_third-party/math/mathjax.swig
  layout/_third-party/schedule.swig
  source/js/src/utils.js
Labels: Optimization, v6.x

#625 Refactor: Add some options for quicklink
  _config.yml
  layout/_third-party/quicklink.swig
Labels: 3rd party service, Feature
