Repository theme-next/hexo-theme-next, pull requests merged in 2019-09, with the labels that each got.

#1068 Use nunjucks-compatible syntax & operator
  layout/_layout.swig
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_partials/analytics/lean-analytics.swig
  layout/_partials/footer.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_partials/header/index.swig
  layout/_partials/header/sub-menu.swig
  layout/_partials/page/breadcrumb.swig
  layout/_partials/post/post-copyright.swig
  layout/_partials/post/post-related.swig
  layout/_partials/post/post-reward.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/facebook-sdk.swig
  layout/_third-party/quicklink.swig
  layout/page.swig
Labels: 🔌 3rd Party Service, 🛠 Improvement

#1149 Fix katex uri
  layout/_third-party/math/katex.swig
Labels: 🐞 Bug Fix, 🔌 3rd Party Service

#1154 Add container for busuanzi counter widget
  layout/_macro/post.swig
  layout/_partials/analytics/busuanzi-counter.swig
Labels: 🛠 Improvement

#1166 Fix fancybox & medium-zoom for hexo asset_img tag
  source/js/next-boot.js
  source/js/utils.js
Labels: 🐞 Bug Fix

#1177 New highlight themes
  _config.yml
  source/css/_common/components/highlight/theme.styl
Labels: ⭐ Feature

#1185 Fix Velocity motion issues
  layout/_partials/sidebar/site-overview.swig
  layout/_scripts/vendors.swig
  source/css/_common/components/post/post-collapse.styl
  source/js/motion.js
  source/js/schemes/muse.js
Labels: 🐞 Bug Fix
