Repository theme-next/hexo-theme-next, pull requests merged in 2019-01, with the labels that each got.

#561 Optimize stylesheet
  layout/_third-party/analytics/busuanzi-counter.swig
  source/css/_common/components/tag-cloud.styl
  source/css/_common/components/third-party/busuanzi-counter.styl
  source/css/_common/components/third-party/third-party.styl
  source/css/_schemes/Gemini/index.styl
Labels: Optimization, v6.x, v7.x

#559 Comment counter
  _config.yml
  layout/_macro/post.swig
  layout/_third-party/analytics/lean-analytics.swig
  layout/_third-party/comments/valine.swig
Labels: Feature, Optimization, v7.x

#557 Using Template literals (Template strings)
  layout/_macro/post.swig
  layout/_partials/header/menu.swig
  layout/_third-party/analytics/lean-analytics.swig
  scripts/filters/after_post_render/exturl.js
  scripts/tags/button.js
  scripts/tags/full-image.js
  scripts/tags/group-pictures.js
  scripts/tags/label.js
  scripts/tags/note.js
  scripts/tags/tabs.js
  source/js/src/algolia-search.js
  source/js/src/scrollspy.js
  source/js/src/utils.js
Labels: Optimization, v7.x

#566 Optimize the loading of comment systems
  layout/_macro/post.swig
  layout/_partials/comments.swig
  layout/_third-party/comments/changyan.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/gitment.swig
  layout/_third-party/comments/index.swig
  layout/_third-party/comments/livere.swig
  layout/_third-party/comments/valine.swig
Labels: Bugfix, v6.x, v7.x

#568 Improve styles of Gitalk & Gitment
  layout/_macro/post.swig
  layout/_partials/comments.swig
  layout/_partials/share/baidushare.swig
  layout/_scripts/schemes/gemini.swig
  layout/_third-party/analytics/analytics-with-widget.swig
  layout/_third-party/analytics/tencent-mta.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/gitment.swig
  source/css/_common/components/footer/footer.styl
  source/css/_common/components/header/github-banner.styl
  source/css/_common/components/pages/breadcrumb.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post-reward.styl
  source/css/_common/components/sidebar/sidebar-feed-link.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_common/components/tags/note-modern.styl
  source/css/_common/components/tags/note.styl
  source/css/_common/components/third-party/gitment.styl
  source/css/_common/scaffolding/tables.styl
  source/css/_schemes/Mist/_header.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: 3rd party service, Bugfix, v6.x, v7.x

#574 Fix #573: [Muse & Mist] Footer is not at the bottom of the page
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_scripts/schemes/mist.swig
  layout/_scripts/schemes/muse.swig
  source/css/_common/components/footer/footer.styl
  source/css/_common/components/highlight/highlight.styl
  source/css/_common/components/sidebar/sidebar-nav.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_common/components/sidebar/site-state.styl
  source/css/_common/outline/outline.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/mobile.styl
  source/js/src/schemes/muse.js
  source/js/src/utils.js
Labels: Bugfix

#580 Edit Google Analytics reference file address
  layout/_third-party/analytics/google-analytics.swig
Labels: Bugfix, v6.x

#582 Reorganize #576, using macro
  .github/PULL_REQUEST_TEMPLATE.md
  _config.yml
  docs/zh-CN/MATH.md
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/github-banner.swig
  layout/_third-party/comments/changyan.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/comments/index.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/copy-code.swig
Labels: Optimization

#519 bugfix: make request time of leancloud saved and let concurrent requests pass
  docs/LEANCLOUD-COUNTER-SECURITY.md
  docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
Labels: Bugfix, Docs, v6.x

#590 Revert using template literals in client side scripts.
  source/js/src/algolia-search.js
  source/js/src/scrollspy.js
  source/js/src/utils.js
Labels: Bugfix

#588 add: details of configuration
  docs/LEANCLOUD-COUNTER-SECURITY.md
Labels: Docs, Optimization
