Repository theme-next/hexo-theme-next, pull requests merged in 2019-11, with the labels that each got.

#1252 Update CDN URLs
  _config.yml
  docs/MATH.md
  docs/zh-CN/MATH.md
  source/css/_common/components/third-party/third-party.styl
Labels: 🛠 Improvement

#1211 Refactor front-matter: make it has the same key as the configuration file
  _config.yml
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/post/post-reward.swig
  layout/_third-party/quicklink.swig
  scripts/filters/front-matter.js
  source/css/_common/components/post/post.styl
Labels: 💥 Breaking Change, 🛠 Improvement

#1263 Make author image optional
  layout/_partials/sidebar/site-overview.swig
Labels: 🛠 Improvement

#1268 Remove include-raw tag
  scripts/tags/include-raw.js
Labels: ⭐ Feature

#1277 Adjust copy-button style
  languages/en.yml
  layout/_partials/head/head.swig
  source/css/_common/scaffolding/highlight/copy-code.styl
  source/css/_common/scaffolding/highlight/highlight.styl
  source/js/utils.js
Labels: ⭐ Feature

#1151 New Crowdin translations
  languages/de.yml
  languages/es.yml
  languages/fa.yml
  languages/fr.yml
  languages/hu.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/uk.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: 🌍 i18n

#1269 Drop NodeJs 8 support & Require NodeJs >= 10
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
  package.json
  scripts/events/index.js
Labels: 💥 Breaking Change

#1281 Set inject default extname from file's extname
  scripts/events/lib/injects.js
Labels: ⭐ Feature

#1284 Remove cheers and auto_excerpt
  _config.yml
  layout/archive.swig
  scripts/filters/post.js
Labels: 💥 Breaking Change

#1247 Allow decoding post link
  scripts/helpers/next-url.js
Labels: 🐞 Bug Fix

#1291 Remove rss button
  _config.yml
  layout/_partials/head/head.swig
  layout/_partials/sidebar/site-overview.swig
  layout/_third-party/statistics/lean-analytics.swig
  scripts/events/lib/config.js
  scripts/filters/locals.js
  scripts/tags/group-pictures.js
  source/css/_common/outline/sidebar/sidebar-button.styl
  source/css/_schemes/Pisces/_sidebar.styl
  source/js/local-search.js
Labels: 💥 Breaking Change

#1073 New Crowdin translations
  languages/de.yml
  languages/es.yml
  languages/fa.yml
  languages/fr.yml
  languages/hu.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/uk.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: 🌍 i18n
