Repository theme-next/hexo-theme-next, pull requests merged in 2019-03, with the labels that each got.

#640 chore: fix typo of bootstrap
  layout/_layout.swig
  layout/_scripts/bootstrap.swig
Labels: Optimization

#641 Rename loader script for prevent wrong boostrap detection in Wappalyzer.
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
  layout/_layout.swig
  layout/_scripts/next-boot.swig
  source/js/src/next-boot.js
Labels: Optimization

#642 Refactor: Improve usage of quicklink
  _config.yml
  layout/_third-party/quicklink/index.swig
Labels: 3rd Party Service, Breaking Change, Discussion, Feature

#648 Feat: Custom font size and color of tagcloud
  _config.yml
  layout/page.swig
Labels: New Feature

#647 New Crowdin translations
  languages/de.yml
  languages/fr.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/vi.yml
Labels: i18n

#657 Refactor back2top button
  _config.yml
  layout/_layout.swig
  layout/_macro/sidebar.swig
  layout/_partials/head/head.swig
  source/css/_common/components/back-to-top.styl
  source/css/_common/components/components.styl
  source/js/src/next-boot.js
  source/js/src/utils.js
Labels: Breaking Change, Optimization

#659 Refactoring pdf.js
  _config.yml
  layout/_third-party/pdf.swig
  scripts/tags/pdf.js
Labels: Breaking Change, Optimization

#662 Fix #1908: Tags amount
  _config.yml
  layout/page.swig
Labels: Feature

#649 Added Mermaid support
  _config.yml
  layout/_layout.swig
  layout/_third-party/mermaid.swig
  scripts/tags/mermaid.js
  source/js/src/js.cookie.js
Labels: Breaking Change, New Feature

#664 Update CDN url in _config.yml
  _config.yml
  layout/_layout.swig
  layout/_scripts/exturl.swig
  layout/_scripts/scroll-cookie.swig
Labels: Optimization

#668 Fix lost tracking_id in google_analytics
  layout/_third-party/analytics/google-analytics.swig
Labels: Bugfix

#667 Fancybox for group-picture and post-gallery
  _config.yml
  layout/_macro/post.swig
  source/js/src/utils.js
Labels: Feature

#671 Remove ua_parser
  .gitignore
  _config.yml
  bower.json
  source/lib/ua-parser-js/dist/ua-parser.min.js
  source/lib/ua-parser-js/dist/ua-parser.pack.js
Labels: Optimization

#676 Add english support for Valine comments
  _config.yml
  layout/_third-party/comments/valine.swig
Labels: Feature

#672 Made a few documentational edits
  README.md
Labels: Optimization

#678 Feat: Add likely share support
  _config.yml
  layout/_macro/post.swig
  layout/_partials/share/likely.swig
  source/css/_common/components/post/post.styl
Labels: New Feature, Roadmap

#669 Fix for issue #645 (and also #658)
  layout/_third-party/math/mathjax.swig
Labels: Bugfix, CSS

#679 Option to display all level of TOC in a post
  _config.yml
  source/css/_common/components/sidebar/sidebar-toc.styl
Labels: Feature, Roadmap

#680 Move stylesheets in .swig to .styl
  _config.yml
  layout/_third-party/comments/gitment.swig
  layout/_third-party/copy-code.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/pdf.swig
  source/css/_common/components/tags/pdf.styl
  source/css/_common/components/tags/tags.styl
  source/css/_common/components/third-party/copy-code.styl
  source/css/_common/components/third-party/gitment.styl
  source/css/_common/components/third-party/math.styl
  source/css/_common/components/third-party/third-party.styl
  source/css/_common/scaffolding/base.styl
Labels: Optimization

#681 Feat: Add chatra and tidio support
  _config.yml
  layout/_layout.swig
  layout/_macro/sidebar.swig
  layout/_third-party/chatra.swig
  layout/_third-party/tidio.swig
  source/css/_common/components/sidebar/sidebar-chat.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: 3rd Party Service, New Feature, Roadmap

#683 Remove unnecessary CSS prefix & update normalize.css
  source/css/_common/components/back-to-top-sidebar.styl
  source/css/_common/components/back-to-top.styl
  source/css/_common/components/post/post-reward.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/sidebar/sidebar-author.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_common/components/third-party/localsearch.styl
  source/css/_common/scaffolding/normalize.styl
  source/css/_mixins/base.styl
  source/css/_schemes/Pisces/_menu.styl
Labels: CSS, v7.x

#688 add icon option for chat button
  _config.yml
  layout/_macro/sidebar.swig
Labels: Feature

#686 Added `safari_rainbow` and `custom_scrollbar`.
  _config.yml
  source/css/_common/components/components.styl
  source/css/_common/components/rainbow.styl
  source/css/_common/components/scrollbar.styl
Labels: New Feature

#682 Added `text_align` option.
  _config.yml
  source/css/_common/components/post/post-expand.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Muse/index.styl
  source/css/_schemes/Pisces/_posts.styl
  source/css/_schemes/Pisces/index.styl
Labels: Feature, Roadmap

#693 Fixed `reward` button vertical align text
  source/css/_common/components/post/post-reward.styl
Labels: Bug Fix, CSS

#695 Refactoring post reward
  _config.yml
  layout/_macro/post.swig
  layout/_partials/post/reward.swig
  source/css/_common/components/post/post-reward.styl
  source/css/_common/components/post/post.styl
Labels: Feature, Roadmap

#684 Bugfix: `back2top` button on mobile, sidebar item margin and sidebar `exturl` link color
  source/css/_common/components/back-to-top-sidebar.styl
  source/css/_common/components/back-to-top.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/sidebar/sidebar-author-links.styl
  source/css/_common/components/sidebar/sidebar-blogroll.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_mixins/Pisces.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: Bug Fix, CSS

#700 Make `site-state-item` centered using `flex`
  source/css/_common/components/sidebar/site-state.styl
Labels: CSS, Optimization, v7.x

#702 Refactored Mist & Muse menu bar using `flex`
  source/css/_common/components/post/post-meta.styl
  source/css/_schemes/Mist/_header.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Muse/_menu.styl
Labels: CSS, Optimization

#677 Extract leancloud-counter to plugins (An example of #663)
  _config.yml
  layout/_layout.swig
  layout/_third-party/analytics/lean-analytics.swig
Labels: New Feature, Roadmap

#706 Remove `qihu_site_verification` and move some options to `SEO Settings`
  _config.yml
  layout/_partials/head/head.swig
  layout/_scripts/vendors.swig
Labels: Optimization

#709 Fix right margin bug on mobile
  source/css/_common/scaffolding/mobile.styl
Labels: Bug Fix

#714 Fixed typo in Baidu.
  _config.yml
  layout/_partials/head/head.swig
Labels: Bug Fix, v6.x

#724 Code style update, using `tablet-mobile()` to make CSS cleaner
  source/css/_common/components/components.styl
  source/css/_common/components/header/github-banner.styl
  source/css/_common/components/header/menu.styl
  source/css/_common/components/pages/pages.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/pages/tag-cloud.styl
  source/css/_common/components/pagination.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post.styl
  source/css/_common/components/sidebar/sidebar-button.styl
  source/css/_common/components/sidebar/sidebar-feed-link.styl
  source/css/_common/components/sidebar/sidebar.styl
  source/css/_common/components/third-party/needsharebutton.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/helpers.styl
  source/css/_common/scaffolding/tables.styl
  source/css/_schemes/Pisces/_brand.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: Optimization

#729 Added CII badge.
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
Labels: Optimization, v6.x

#728 Remove redundant styles
  source/css/_common/components/header/github-banner.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post-expand.styl
  source/css/_common/components/sidebar/sidebar-button.styl
  source/css/_common/components/sidebar/sidebar-toggle.styl
  source/css/_mixins/base.styl
Labels: Optimization, v6.x

#725 Move some docs from `_config.yml` to theme-next.org site
  _config.yml
Labels: Docs, Roadmap, v6.x

#727 Update README.md, remove unused URLs
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
Labels: Docs, v6.x

#730 Added «Reporting Security Bugs» sections.
  .github/CONTRIBUTING.md
  docs/zh-CN/CONTRIBUTING.md
Labels: Docs, v6.x

#733 Changed Riot chat link.
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
Labels: Docs, v6.x

#735 Fix #734: Sidebar button style on Pisces and Gemini
  source/css/_schemes/Pisces/_sidebar.styl
Labels: Bug Fix, CSS

#739 Added «Thanks» section
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
Labels: Docs, v6.x

#747 docs: update CONTRIBUTING.md
  .github/CONTRIBUTING.md
  docs/zh-CN/CONTRIBUTING.md
Labels: Docs, v6.x

#738 Using macro to make CSS simpler
  source/css/_common/components/buttons.styl
  source/css/_common/components/header/menu.styl
  source/css/_common/components/header/site-nav.styl
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-eof.styl
  source/css/_common/components/post/post-meta.styl
  source/css/_common/components/post/post-nav.styl
  source/css/_common/components/post/post-reading_progress.styl
  source/css/_common/components/post/post-type.styl
  source/css/_common/components/rainbow.styl
  source/css/_common/components/sidebar/sidebar-author-links.styl
  source/css/_common/components/sidebar/sidebar-author.styl
  source/css/_common/components/sidebar/sidebar-dimmer.styl
  source/css/_common/components/sidebar/sidebar-toc.styl
  source/css/_common/components/sidebar/site-state.styl
  source/css/_common/components/tags/blockquote-center.styl
  source/css/_common/components/tags/tabs.styl
  source/css/_common/components/third-party/algolia-search.styl
  source/css/_common/components/third-party/gitment.styl
  source/css/_common/components/third-party/related-posts.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/helpers.styl
  source/css/_schemes/Mist/_header.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Mist/_search.styl
  source/css/_schemes/Muse/_layout.styl
  source/css/_schemes/Muse/_menu.styl
  source/css/_schemes/Muse/_search.styl
  source/css/_schemes/Pisces/_brand.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_menu.styl
  source/css/_schemes/Pisces/_sidebar.styl
Labels: CSS, Improvement

#748 Improved canonical path for vision in Google.
  _config.yml
  layout/_partials/head/head-unique.swig
  scripts/tags/button.js
  scripts/tags/exturl.js
  scripts/tags/full-image.js
  scripts/tags/group-pictures.js
  scripts/tags/label.js
  scripts/tags/mermaid.js
  scripts/tags/note.js
  scripts/tags/pdf.js
  scripts/tags/tabs.js
  scripts/tags/video.js
Labels: Improvement, v6.x

#750 Merged note.styl & note-modern.styl
  source/css/_common/components/tags/note-modern.styl
  source/css/_common/components/tags/note.styl
  source/css/_common/components/tags/tags.styl
Labels: CSS, Improvement, v6.x

#752 Fix Mathjax style issue
  source/css/_common/components/third-party/math.styl
  source/css/_common/components/third-party/third-party.styl
Labels: Bug Fix, Improvement, v7.x

#756 Contributors per line: 6 instead of 7
  .all-contributorsrc
Labels: Docs, v6.x

#744 Reduce the use of `!important` for GitHub banner
  layout/_partials/github-banner.swig
  source/css/_common/components/header/github-banner.styl
  source/css/_common/components/post/post-eof.styl
  source/css/_schemes/Gemini/index.styl
Labels: CSS, Improvement, v6.x

#763 Removed `no-wrap` style from label tag
  source/css/_common/components/tags/label.styl
Labels: Bug Fix, CSS, v6.x

#765 From now release drafts will maked automatically
  .github/release-drafter.yml
Labels: Improvement

#766 Improved console warning for non-supporting
  scripts/tags/exturl.js
Labels: Improvement, JavaScript

#767 Changes comparison for Release Drafter Bot
  .github/release-drafter.yml
Labels: Improvement

#768 Added `Improvement Need` label
  .github/CONTRIBUTING.md
  docs/zh-CN/CONTRIBUTING.md
Labels: Docs, v6.x

#769 Breadcrumbs now work with both `*.html` and `index.html` pages
  layout/_partials/page/breadcrumb.swig
Labels: Bug Fix, v6.x

#751 Moved `source/js/src` to `source/js`
  docs/ALGOLIA-SEARCH.md
  docs/zh-CN/ALGOLIA-SEARCH.md
  gulpfile.coffee
  layout/_scripts/commons.swig
  layout/_scripts/exturl.swig
  layout/_scripts/next-boot.swig
  layout/_scripts/pages/post-details.swig
  layout/_scripts/schemes/muse.swig
  layout/_scripts/schemes/pisces.swig
  layout/_scripts/scroll-cookie.swig
  layout/_third-party/search/algolia-search.swig
  source/js/affix.js
  source/js/algolia-search.js
  source/js/exturl.js
  source/js/js.cookie.js
  source/js/motion.js
  source/js/next-boot.js
  source/js/post-details.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/scroll-cookie.js
  source/js/scrollspy.js
  source/js/utils.js
Labels: Improvement, v6.x
