Repository theme-next/hexo-theme-next, pull requests merged in 2019-10, with the labels that each got.

#1180 Improve the style of site-nav
  layout/_macro/sidebar.swig
  layout/_partials/header/brand.swig
  source/css/_common/components/post/post-header.styl
  source/css/_common/outline/header/menu.styl
  source/css/_common/outline/header/site-nav.styl
  source/css/_common/outline/sidebar/sidebar-toggle.styl
  source/css/_common/scaffolding/buttons.styl
  source/css/_common/scaffolding/scaffolding.styl
  source/css/_common/scaffolding/toggles.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Muse/_menu.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_menu.styl
  source/js/next-boot.js
  source/js/schemes/muse.js
Labels: ⭐ Feature

#1140 Optimize the loading of three.js
  _config.yml
  layout/_scripts/three.swig
  layout/_scripts/vendors.swig
Labels: 🛠 Improvement

#1193 New Valine options
  _config.yml
  layout/_third-party/comments/valine.swig
Labels: ⭐ Feature

#1175 Fix compatibility issues with hexo-util@1.3.0
  layout/_partials/pagination.swig
  scripts/helpers/next-url.js
Labels: Hexo, 🛠 Improvement

#1199 Add lang attribute to article tag when specified in front matter
  layout/_layout.swig
  layout/_macro/post.swig
  layout/archive.swig
  layout/category.swig
  layout/index.swig
  layout/page.swig
  layout/post.swig
  layout/tag.swig
  source/css/_common/components/post/post-eof.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_posts-expand.styl
Labels: 🛠 Improvement

#1155 New README for NexT
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .travis.yml
  README.md
  docs/INSTALLATION.md
  docs/UPDATE-FROM-5.1.X.md
  docs/ru/INSTALLATION.md
  docs/ru/README.md
  docs/ru/UPDATE-FROM-5.1.X.md
  docs/zh-CN/CODE_OF_CONDUCT.md
  docs/zh-CN/CONTRIBUTING.md
  docs/zh-CN/INSTALLATION.md
  docs/zh-CN/README.md
  docs/zh-CN/UPDATE-FROM-5.1.X.md
Labels: 📖 Docs

#1198 Add Google Analytics Pageview
  _config.yml
  layout/_third-party/analytics/google-analytics-pageview.swig
  layout/_third-party/analytics/index.swig
Labels: 🌟 New Feature

#1202 Point to different website based on the scheme
  layout/_partials/footer.swig
Labels: ⭐ Feature

#1197 Code style update
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_partials/footer.swig
  layout/_partials/header/menu.swig
  layout/_partials/page/page-header.swig
  layout/_partials/post-edit.swig
  layout/_partials/post/post-copyright.swig
  layout/_third-party/analytics/google-analytics.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/facebook-sdk.swig
  layout/category.swig
  layout/page.swig
  layout/tag.swig
  scripts/filters/comment/changyan.js
  scripts/filters/comment/disqus.js
  scripts/filters/comment/disqusjs.js
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/valine.js
Labels: 🛠 Improvement

#1209 Replace id with class name
  layout/_layout.swig
  layout/_partials/footer.swig
  layout/_partials/post/post-reward.swig
  layout/_scripts/pages/schedule.swig
  layout/page.swig
  source/css/_common/components/pages/schedule.styl
  source/css/_common/components/post/post-copyright.styl
  source/css/_common/components/post/post-gallery.styl
  source/css/_common/components/post/post-reward.styl
  source/css/_common/components/post/post-widgets.styl
  source/css/_common/components/third-party/search.styl
  source/css/_common/outline/footer/footer.styl
  source/css/_common/outline/header/header.styl
  source/css/_common/outline/outline.styl
  source/css/_common/outline/sidebar/sidebar-nav.styl
  source/css/_common/scaffolding/base.styl
  source/css/_common/scaffolding/tags/tabs.styl
  source/css/_schemes/Gemini/index.styl
  source/css/_schemes/Mist/_menu.styl
  source/css/_schemes/Mist/index.styl
  source/css/_schemes/Muse/_layout.styl
  source/css/_schemes/Pisces/_layout.styl
  source/css/_schemes/Pisces/_menu.styl
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
  source/js/utils.js
Labels: CSS, 🛠 Improvement

#1058 Make font-size customized only when `theme.font.enable` is true
  _config.yml
  source/css/_variables/base.styl
Labels: Configurations, ⭐ Feature, 🌀 Fonts

#1205 Code style update
  layout/_partials/head/head-unique.swig
  layout/_partials/head/head.swig
  layout/_scripts/pages/schedule.swig
  layout/_third-party/comments/valine.swig
  scripts/events/lib/config.js
  scripts/events/lib/injects.js
  scripts/helpers/font.js
  scripts/helpers/next-url.js
  scripts/tags/include-raw.js
  source/css/_variables/base.styl
Labels: Template Engine, 🛠 Improvement

#1215 Migrate to Nunjucks [0]
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_macro/sidebar.swig
  layout/_partials/footer.swig
  layout/_partials/head/head.swig
  layout/_partials/header/menu-item.swig
  layout/_partials/post/post-copyright.swig
  layout/_partials/post/post-related.swig
  layout/_partials/sidebar/site-overview.swig
  layout/_scripts/schemes/gemini.swig
  layout/_scripts/schemes/mist.swig
  layout/_scripts/three.swig
  layout/_scripts/vendors.swig
  layout/_third-party/chat/index.swig
  layout/_third-party/comments/disqusjs.swig
  layout/_third-party/comments/gitalk.swig
  layout/_third-party/comments/valine.swig
  layout/_third-party/index.swig
  layout/_third-party/math/index.swig
  layout/_third-party/math/katex.swig
  layout/_third-party/math/mathjax.swig
  layout/_third-party/quicklink.swig
  layout/_third-party/search/algolia-search.swig
  layout/_third-party/search/index.swig
  layout/_third-party/tags/index.swig
  layout/_third-party/tags/mermaid.swig
  layout/_third-party/tags/pdf.swig
  layout/index.swig
  layout/post.swig
Labels: ⭐ Feature

#1222 Update Contributors part in README
  .all-contributorsrc
  README.md
  docs/AUTHORS.md
  docs/ru/README.md
  docs/zh-CN/README.md
  package.json
Labels: 📖 Docs

#1226 Migrate to Nunjucks [3]
  layout/_macro/post.swig
  layout/_partials/footer.swig
  layout/_third-party/comments/disqus.swig
  layout/_third-party/math/index.swig
  scripts/events/lib/config.js
  scripts/filters/excerpt.js
  scripts/filters/exturl.js
  scripts/filters/lazyload.js
  scripts/filters/locals.js
  scripts/filters/post.js
  scripts/helpers/engine.js
  scripts/helpers/next-url.js
  scripts/renderer.js
Labels: ⭐ Feature

#1213 Fix known issues
  layout/_partials/sidebar/site-overview.swig
  source/js/utils.js
Labels: 🐞 Bug Fix

#1143 New canonical tag helper
  layout/_partials/head/head-unique.swig
  scripts/helpers/engine.js
Labels: 🛠 Improvement

#732 Code style update
  README.md
  docs/ru/README.md
  docs/zh-CN/README.md
  gulpfile.js
  layout/_partials/comments.swig
  scripts/filters/default-injects.js
  scripts/filters/post.js
  scripts/helpers/font.js
  source/js/local-search.js
  source/js/utils.js
Labels: 🛠 Improvement

#1230 Replace lodash with native API
  scripts/events/index.js
  scripts/events/lib/config.js
Labels: 🛠 Improvement

#963 Delete query strings
  layout/_partials/head/head.swig
  layout/_scripts/vendors.swig
  scripts/helpers/engine.js
Labels: ⭐ Feature

#1232 Extract some features to plugins
  _config.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/head/head.swig
  layout/_partials/post/post-footer.swig
  layout/_partials/post/wechat-subscriber.swig
  layout/_third-party/analytics/application-insights.swig
  layout/_third-party/analytics/index.swig
  layout/_third-party/facebook-sdk.swig
  layout/_third-party/index.swig
  layout/_third-party/math/index.swig
  layout/_third-party/vkontakte-api.swig
  scripts/filters/comment/facebook-comments-plugin.js
  scripts/filters/comment/vkontakte.js
  source/css/_common/components/components.styl
  source/css/_common/components/post/post-widgets.styl
  source/css/_common/components/scrollbar.styl
Labels: ⭐ Feature
