Repository theme-next/hexo-theme-next, pull requests merged in 2020-03, with the labels that each got.

#1401 Arabic translation
  languages/ar.yml
Labels: 🌍 i18n

#1074 New Crowdin translations
  languages/ar.yml
  languages/ru.yml
  languages/uk.yml
  languages/zh-CN.yml
Labels: 🌍 i18n

#1394 Optimize the loading of exturl
  source/css/_common/components/post/post.styl
  source/css/_common/scaffolding/base.styl
  source/js/utils.js
Labels: 🛠 Improvement

#1400 Drop PDFObject
  _config.yml
  layout/_third-party/tags/pdf.swig
  scripts/tags/pdf.js
  source/css/_common/scaffolding/tags/pdf.styl
  source/js/utils.js
Labels: 🔌 3rd Party Plugin, 🛠 Improvement

#1409 Fix dark styles of buttons
  source/css/_colors.styl
  source/css/_common/scaffolding/buttons.styl
  source/css/_common/scaffolding/comments.styl
  source/css/_schemes/Mist/_posts-expand.styl
  source/css/_schemes/Muse/_header.styl
  source/css/_variables/base.styl
Labels: CSS, 🛠 Improvement

#1418 Escaping html in search results
  source/js/local-search.js
Labels: 🐞 Bug Fix

#1391 Multilingual switch button support
  _config.yml
  languages/en.yml
  layout/_layout.swig
  layout/_macro/post.swig
  layout/_partials/head/head-unique.swig
  layout/_partials/languages.swig
  layout/_scripts/pjax.swig
  layout/page.swig
  scripts/filters/locals.js
  scripts/helpers/engine.js
  source/css/_common/outline/footer/footer.styl
  source/js/next-boot.js
  source/js/utils.js
Labels: 💥 Breaking Change

#1426 New leancloud_visitors option server_url
  _config.yml
  docs/LEANCLOUD-COUNTER-SECURITY.md
  docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
  layout/_third-party/statistics/lean-analytics.swig
Labels: ⭐ Feature

#1427 Animation for search-popup
  source/css/_common/components/third-party/search.styl
  source/css/_common/scaffolding/highlight/highlight.styl
  source/js/algolia-search.js
  source/js/local-search.js
Labels: CSS, 🛠 Improvement

#1414 Remove `seo` option in `_config.yml`
  _config.yml
  layout/_macro/post-collapse.swig
  layout/_macro/post.swig
  layout/_partials/header/brand.swig
  layout/_partials/header/index.swig
  layout/_partials/header/menu.swig
  layout/_partials/page/page-header.swig
  layout/_partials/search/index.swig
  layout/category.swig
  layout/tag.swig
  source/css/_common/components/post/post-collapse.styl
  source/css/_common/components/post/post-header.styl
  source/css/_common/outline/header/site-meta.styl
  source/css/_variables/base.styl
Labels: Backlog, 💥 Breaking Change

#1432 Simplify footer.powered settings
  _config.yml
  languages/en.yml
  layout/_partials/footer.swig
Labels: ⭐ Feature

#1413 New Crowdin translations
  languages/ar.yml
  languages/de.yml
  languages/es.yml
  languages/fa.yml
  languages/fr.yml
  languages/hu.yml
  languages/id.yml
  languages/it.yml
  languages/ja.yml
  languages/ko.yml
  languages/nl.yml
  languages/pt-BR.yml
  languages/pt.yml
  languages/ru.yml
  languages/tr.yml
  languages/uk.yml
  languages/vi.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
Labels: 🌍 i18n
