Repository theme-next/hexo-theme-next, pull requests merged in 2020-01, with the labels that each got.

#1349 Fix conflict between animation of sub-menu icons and pjax
  layout/_scripts/pjax.swig
  source/js/motion.js
Labels: 🐞 Bug Fix

#1351 Fix valine & disqus meta for #1305
  scripts/filters/comment/disqus.js
  scripts/filters/comment/valine.js
Labels: 🐞 Bug Fix

#1358 Improve french translation
  languages/fr.yml
Labels: 🌍 i18n

#1360 feat: follow me through various channels
  _config.yml
  languages/en.yml
  languages/zh-CN.yml
  languages/zh-HK.yml
  languages/zh-TW.yml
  layout/_macro/post.swig
  layout/_partials/post/post-followme.swig
  source/css/_common/components/post/post-followme.styl
  source/css/_common/components/post/post.styl
Labels: 🌟 New Feature
