Repository theme-next/hexo-theme-next, pull requests merged in 2020-05, with the labels that each got.

#1463 Optimize version condition
  scripts/events/index.js
Labels: 🐞 Bug Fix

#1464 Fix tables text align
  source/css/_common/scaffolding/tables.styl
Labels: 🐞 Bug Fix

#1470 Fix: bind event DOMContentLoaded on document insteadof window
  source/js/algolia-search.js
  source/js/bookmark.js
  source/js/local-search.js
  source/js/next-boot.js
  source/js/schemes/muse.js
  source/js/schemes/pisces.js
Labels: 🐞 Bug Fix

#1471 beautufy the reward button
  source/css/_common/components/post/post-reward.styl
Labels: ⭐ Feature

#1482 Update baidupush
  layout/_third-party/baidu-push.swig
Labels: 🛠 Improvement

#1453 Optimize language selector
  source/js/utils.js
Labels: 🛠 Improvement
